# Generated by Django 3.0.5 on 2020-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan_number', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=300)),
            ],
        ),
    ]
