# Generated by Django 3.0.5 on 2020-04-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
