# Generated by Django 3.0.5 on 2020-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
