# Generated by Django 3.0.5 on 2020-04-23 17:51

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200423_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(max_length=20, unique=True, validators=[myapp.models.validate_pan_number]),
        ),
    ]
