# Generated by Django 3.0.5 on 2020-04-23 17:51

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200423_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_name]),
        ),
    ]
